routes/web.php
<?php

use App\Http\Controllers\Admin;
use App\Http\Controllers\Voter;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * Voter area
 */
Route::get('/', [Voter\LoginController::class, 'showLoginForm'])->name('voter.index');
Route::post('/', [Voter\LoginController::class, 'login'])->name('voter.login');
Route::get('/exit', [Voter\LoginController::class, 'logout'])->name('voter.logout');

Route::middleware('auth:web-voter')->group(function () {
    Route::get('/vote', [Voter\PropositionController::class, 'index'])->name('proposition.index');
    Route::post('/vote', [Voter\PropositionController::class, 'update'])->name('proposition.update');
});

/*
 * Admin area
 */
Route::get('/admin/login', [Admin\LoginController::class, 'showLoginForm'])->name('admin.login.show');
Route::post('/admin/login', [Admin\LoginController::class, 'login'])->name('admin.login.update');
Route::get('/admin/logout', [Admin\LoginController::class, 'logout'])->name('admin.login.logout');

Route::prefix('/admin')->middleware('auth:web-admin')->name('admin.')->group(function () {
    Route::get('/', [Admin\DashboardController::class, 'index'])->name('index');

    Route::get('/voters', [Admin\VoterController::class, 'index'])->name('voters.index');
    Route::post('/voters', [Admin\VoterController::class, 'update'])->name('voters.update');
    Route::get('/voters/{voter}/delete', [Admin\VoterController::class, 'destroy'])->name('voters.destroy');

    Route::resource('propositions', Admin\PropositionController::class)->except(['show']);

    Route::get('/export', [Admin\ResultExportController::class, 'index'])->name('export.index');

    Route::get('/config', [Admin\AppConfigController::class, 'index'])->name('config.index');
    Route::post('/config', [Admin\AppConfigController::class, 'update'])->name('config.update');
});

app/Models/Proposition.php
<?php

namespace App\Models;

use App\Events\PropositionChange;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;

class Proposition extends AbstractModel
{
    use HasFactory;

    protected $fillable = ['title', 'is_open', 'type', 'order', 'blank_option_id', 'abstain_option_id'];

    protected $casts = [
        'is_open' => 'bool',
    ];

    protected $dispatchesEvents = [
        'saved' => PropositionChange::class,
    ];

    public function scopeOpen(Builder $query): Builder
    {
        return $query->where('is_open', true);
    }

    public function options(): HasMany
    {
        return $this
            ->hasMany(PropositionOption::class)
            ->orderBy('sort_order')
            ->when(
                $this->blank_option_id,
                fn (Builder $query, string $optionId) => $query->where('id', '!=', $optionId)
            )
            ->when(
                $this->abstain_option_id,
                fn (Builder $query, string $optionId) => $query->where('id', '!=', $optionId)
            );
    }

    public function blankOption(): BelongsTo
    {
        return $this->belongsTo(PropositionOption::class, 'blank_option_id');
    }

    public function abstainOption(): BelongsTo
    {
        return $this->belongsTo(PropositionOption::class, 'abstain_option_id');
    }

    public function hasBlank(): bool
    {
        return !is_null($this->blank_option_id);
    }

    public function hasAbstain(): bool
    {
        return !is_null($this->abstain_option_id);
    }

    public function verticalOptions(): Collection
    {
        return $this->options->where('axis', 'vertical');
    }

    public function horizontalOptions(): Collection
    {
        return $this->options->where('axis', 'horizontal');
    }

    public function voters(): HasManyThrough
    {
        return $this->hasManyThrough(
            Voter::class,
            VoterPropositionOption::class,
            'proposition_id',
            'id',
            'id',
            'voter_id'
        );
    }

    public function answers(): HasMany
    {
        return $this->hasMany(VoterPropositionOption::class);
    }
}

app/Http/Controllers/Admin/Api/PropositionController.php
<?php


namespace App\Http\Controllers\Admin\Api;

use App\Http\Requests\Admin\Api\PropositionUpdateRequest;
use App\Models\Proposition;
use Illuminate\Http\JsonResponse;

class PropositionController
{
    public function update(PropositionUpdateRequest $request, Proposition $proposition): JsonResponse
    {
        $proposition->update($request->validated());
        return response()->json($proposition);
    }
}

app/Http/Controllers/Admin/PropositionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\PropositionStoreRequest;
use App\Http\Requests\Admin\PropositionUpdateRequest;
use App\Models\Proposition;
use App\VoteSystem\Pages\Admin\PropositionIndexPage;
use App\VoteSystem\Repositories\PropositionRepository;
use App\VoteSystem\Repositories\VoterRepository;
use App\VoteSystem\Services\PropositionService;
use Exception;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class PropositionController extends Controller
{
    public function __construct(
        private readonly PropositionService $propositionService,
        private readonly PropositionRepository $propositionRepository,
        private readonly VoterRepository $voterRepository
    ) {
        parent::__construct();
    }

    public function index(): View
    {
        $propositions = $this->propositionRepository->findAll(['options', 'answers']);
        $voterStatistics = $this->voterRepository->aggregateVoterStatistics();

        return $this->page(new PropositionIndexPage($propositions, $voterStatistics));
    }

    public function create(): View
    {
        $nextPropositionOrder = $this->propositionService->getNextPropositionOrder();
        $mappedOldOptions = $this->propositionService
            ->mapOptions(old('options', []))
            ->all();

        return view('views.admin.propositions.create', [
            'nextPropositionOrder' => $nextPropositionOrder,
            'mappedOldOptions' => $mappedOldOptions,
        ]);
    }

    public function update(PropositionUpdateRequest $request, Proposition $proposition): RedirectResponse
    {
        $this->propositionService->updateProposition(
            $proposition,
            $request->validated()
        );

        return redirect()->route('admin.propositions.index');
    }

    public function store(PropositionStoreRequest $request): RedirectResponse
    {
        $this->propositionService->createProposition($request->validated());

        return redirect()->route('admin.propositions.index');
    }

    public function edit(Proposition $proposition): View
    {
        $mappedOldOptions = $this->propositionService->mapOptions(
            old('options', [])
        );

        $mappedOldOptions = $mappedOldOptions->count() > 0
            ? $mappedOldOptions
            : $proposition->options()->get();

        return view('views.admin.propositions.edit', [
            'proposition' => $proposition,
            'mappedOldOptions' => $mappedOldOptions,
        ]);
    }

    /**
     * @throws Exception
     */
    public function destroy(Proposition $proposition): RedirectResponse
    {
        $proposition->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/Voter/PropositionController.php
<?php

namespace App\Http\Controllers\Voter;

use App\Http\Controllers\Controller;
use App\Models\Proposition;
use App\VoteSystem\Services\PropositionService;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class PropositionController extends Controller
{
    public function __construct(private readonly PropositionService $propositionService)
    {
        parent::__construct();
    }

    public function index(Request $request): View
    {
        $user = $request->user();
        $proposition = $this->propositionService->getNextProposition($user);

        return $this->show($request, $proposition);
    }

    public function show(Request $request, ?Proposition $proposition): View
    {
        $answeredPropositionIds = $request->user()
            ->answers()
            ->distinct('proposition_id')
            ->get(['proposition_id'])
            ->pluck('proposition_id');

        return view('views.voter.show', [
            'proposition' => $proposition,
            'answeredPropositions' => $answeredPropositionIds
        ]);
    }
}

resources/views/views/admin/propositions/create.blade.php
@extends('layouts.admin')

@section('content')
    <form
        method="POST"
        action="{{ route('admin.propositions.store') }}"
        class="flex flex-col items-stretch px-8 sm:px-0 w-full lg:w-3/4 xl:w-1/2"
    >
        <h1 class="title">@lang('Create proposition')</h1>
        @csrf

        <div>
            <x-form.textfield name='title' required placeholder='Is it okay to put pineapple on pizza?' label='Title' />

            <x-form.textfield name='order' required placeholder='1' type='number' label='Order' min='1' />

            <x-form.checkbox
                name='has_abstain'
                label='Has abstain option'
                :hint='__("Abstain option explanation")'
            />

            <x-form.checkbox
                name='has_blank'
                label='Has blank option'
                :hint='__("Blank option explanation")'
            />
        </div>

        <proposition-option-editor
            :errors='@json($errors->get('options.*'))'
            :source-options='@json($mappedOldOptions)'
            initial-type="list"
        ></proposition-option-editor>

        <x-form.button type='submit'>@lang('Create')</x-form.button>
    </form>
@endsection

resources/views/views/admin/propositions/edit.blade.php
@extends('layouts.admin')

@section('content')
    <form
        method="POST"
        action="{{ route('admin.propositions.update', $proposition) }}"
        class="flex flex-col items-stretch px-8 sm:px-0 w-full lg:w-3/4 xl:w-1/2"
    >
        <h1 class="title">@lang('Edit proposition')</h1>
        @csrf
        @method('PUT')

        <div class="">
            <x-form.textfield
                name='title'
                placeholder='Is it okay to put pineapple on pizza?'
                label='Title'
                :value='$proposition->title'
                required />

            <x-form.textfield
                name='order'
                placeholder='1'
                type='number'
                label='Order'
                min='1'
                :value='$proposition->order'
                required
            />

            <x-form.checkbox
                name='has_abstain'
                :checked='$proposition->hasAbstain()'
                label='Has abstain option'
                :hint='__("Abstain option explanation")'
            />

            <x-form.checkbox
                name='has_blank'
                :checked='$proposition->hasBlank()'
                label='Has blank option'
                :hint='__("Blank option explanation")'
            />
        </div>

        <proposition-option-editor
            :errors='@json($errors->get('options.*'))'
            :source-options='@json($mappedOldOptions)'
            initial-type="{{ $proposition->type }}"
        ></proposition-option-editor>

        <x-form.button type='submit'>@lang('Update')</x-form.button>
    </form>
@endsection

resources/views/views/admin/propositions/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-24">
        <h1 class="title col-span-1 lg:col-span-2 px-8 sm:px-0 text-primary">@lang('Dashboard')</h1>
        <div class="banner col-span-1 lg:col-span-2">{{--
        --}}@lang('Voter statistics', ['total' => $page->getTotalVoterCount(), 'used' => $page->getUsedVoterCount() ])
            <br />
            @lang('These statistics are based on the used tokens.')
        </div>

        <a class="col-span-1 lg:col-span-2" href="{{ route('admin.export.index') }}">
            @lang('Click here to export the voting results to Excel')
        </a>

        @foreach($page->getPropositions() as $proposition)
            <div class="card">
                <div class="card-header">
                    <h2 class="title flex-1 truncate">{{ $proposition->order }}. {{ $proposition->title }}</h2>
                    <span class="badge {{ $proposition->is_open ? 'badge--accent' : '' }}">
                        @lang($proposition->is_open ? 'Open' : 'Closed')
                    </span>
                </div>

                <div class="card-content">
                    @if($proposition->type === 'list')
                        <h3 class="sub-title">{{ $page->getListQuestion($proposition)->option }}</h3>
                        @foreach($page->getListOptions($proposition) as $option)
                            @php
                                $count = $page->getOptionCount($proposition, $option);
                                $width = $count / ($page->getUsedVoterCount() ?: 1)
                            @endphp
                            <list-result-option
                                option='{{ $option->option }}'
                                :count='{{ $count }}'
                                :total='{{ $page->getUsedVoterCount() }}'
                                :show-bar='{{ $option->id !== $proposition->abstainId ? 'true' : 'false' }}'
                            ></list-result-option>
                        @endforeach
                    @elseif($proposition->type === 'grid')
                        <div class="table-wrapper">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th></th>
                                    @foreach($proposition->horizontalOptions() as $option)
                                        <th>{{ __($option->option) }}</th>
                                    @endforeach
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($proposition->verticalOptions() as $rowOption)
                                    <tr>
                                        <th>{{ $rowOption->option }}</th>
                                        @foreach($proposition->horizontalOptions() as $colOption)
                                            <td>{{ $page->getOptionCount($proposition, $rowOption, $colOption) }}</td>
                                        @endforeach
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endif
                </div>

                <div class="card-footer">
                    <a
                        href="{{ route('admin.propositions.edit', $proposition) }}"
                        class="card-footer-link text-gray-600"
                    >@lang('Edit')</a>
                </div>
            </div>
        @endforeach
    </div>
    <a
        class="fixed bottom-0 right-0 rounded-full bg-accent m-4 sm:m-8 p-2 w-16 h-16 sm:w-20 sm:h-20 shadow-lg z-10"
        href="{{ route('admin.propositions.create') }}"
        title="@lang('Create proposition')"
    >
        <svg viewBox="0 0 24 24" class="w-full h-full text-white">
            <path fill="currentColor" fill-rule="evenodd"
                  d="M17 11a1 1 0 0 1 0 2h-4v4a1 1 0 0 1-2 0v-4H7a1 1 0 0 1 0-2h4V7a1 1 0 0 1 2 0v4h4z" />
        </svg>
    </a>
@endsection