routes/web.php
<?php

use App\Http\Controllers\Admin;
use App\Http\Controllers\Voter;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * Voter area
 */
Route::get('/', [Voter\LoginController::class, 'showLoginForm'])->name('voter.index');
Route::post('/', [Voter\LoginController::class, 'login'])->name('voter.login');
Route::get('/exit', [Voter\LoginController::class, 'logout'])->name('voter.logout');

Route::middleware('auth:web-voter')->group(function () {
    Route::get('/vote', [Voter\PropositionController::class, 'index'])->name('proposition.index');
    Route::post('/vote', [Voter\PropositionController::class, 'update'])->name('proposition.update');
});

/*
 * Admin area
 */
Route::get('/admin/login', [Admin\LoginController::class, 'showLoginForm'])->name('admin.login.show');
Route::post('/admin/login', [Admin\LoginController::class, 'login'])->name('admin.login.update');
Route::get('/admin/logout', [Admin\LoginController::class, 'logout'])->name('admin.login.logout');

Route::prefix('/admin')->middleware('auth:web-admin')->name('admin.')->group(function () {
    Route::get('/', [Admin\DashboardController::class, 'index'])->name('index');

    Route::get('/voters', [Admin\VoterController::class, 'index'])->name('voters.index');
    Route::post('/voters', [Admin\VoterController::class, 'update'])->name('voters.update');
    Route::get('/voters/{voter}/delete', [Admin\VoterController::class, 'destroy'])->name('voters.destroy');

    Route::resource('propositions', Admin\PropositionController::class)->except(['show']);

    Route::get('/export', [Admin\ResultExportController::class, 'index'])->name('export.index');

    Route::get('/config', [Admin\AppConfigController::class, 'index'])->name('config.index');
    Route::post('/config', [Admin\AppConfigController::class, 'update'])->name('config.update');
});

resources/views/views/admin/config/index.blade.php
@extends('layouts.admin')

@section('content')
    <form action="{{ route('admin.config.update') }}" method="POST" class="px-8 sm:px-0">
        @csrf
        <h1 class="title">@lang('Config management')</h1>
        <p class="mt-2 text-gray-600">
            @lang('On this page you can control certain settings used throughout the application.')
        </p>
        <p class="mt-2 text-gray-800">
            @lang('Config warning')
        </p>
        <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6 pt-6">
            @foreach($settings as $setting)
                <div class="p-2 rounded shadow">
                    <label class="font-mono w-full mb-2" for="{{ $setting->name }}">
                        @lang('appconfig.' . $setting->name)
                    </label>
                    <textarea
                        id="{{ $setting->name }}"
                        class="input h-auto w-full resize-y"
                        rows="3"
                        name="{{ $setting->name }}"
                        placeholder="{{ $setting->default }}"
                    >{!! $setting->value !!}</textarea>
                    @error($setting->name)
                    <span class="text-failure text-sm font-normal w-full">@lang($message)</span>
                    @enderror
                </div>
            @endforeach
        </div>
        <input type="submit" value="@lang('Save')" class="submit-button"/>
    </form>
@endsection